version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - .docker/rabbitmq/:/var/lib/rabbitmq/
      - .docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - network

  migrate:
    build: 
      context: ./internal/infra/database/migrations/
      dockerfile: "Dockerfile"
    container_name: migrate
    networks:
        - network
    volumes:
        - ./internal/infra/database/migrations:/migrations
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s migrate
    command: ["-path", "/migrations", "-database",  "mysql://root:root@tcp(mysql:3306)/orders", "-verbose","up"]
    links: 
        - mysql
    depends_on:
      - mysql

  go-app:
    build: 
      context: ./
      dockerfile: "Dockerfile"
    restart: always
    container_name: go-app
    ports:
      - "8000:8000"
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - network

networks:
  network: {}